const MedicationsList = [
    { label: "Aspirina", value: "Aspirina" },
    { label: "Betabloqueadores", value: "Betabloqueadores" },
    { label: "Estatinas", value: "Estatinas" },
    { label: "Inibidores da Enzima Conversora de Angiotensina (IECA)", value: "IECA" },
    { label: "Bloqueadores dos Canais de Cálcio", value: "Bloqueadores dos Canais de Cálcio" },
    { label: "Diuréticos", value: "Diuréticos" },
    { label: "Anticoagulantes", value: "Anticoagulantes" },
    { label: "Antiplaquetários", value: "Antiplaquetários" },
    { label: "Nitratos", value: "Nitratos" },
    { label: "Antiarrítmicos", value: "Antiarrítmicos" },
    { label: "Cloreto de Potássio", value: "Cloreto de Potássio" },
    { label: "Digoxina", value: "Digoxina" },
    { label: "Ivabradina", value: "Ivabradina" },
    { label: "Ezetimiba", value: "Ezetimiba" },
    { label: "Fibratos", value: "Fibratos" },
    { label: "Antagonistas da Aldosterona", value: "Antagonistas da Aldosterona" },
    { label: "Angiotensina II", value: "Angiotensina II" },
    { label: "Trimetazidina", value: "Trimetazidina" },
    { label: "Sartan", value: "Sartan" },
    { label: "Atorvastatina", value: "Atorvastatina" },
    { label: "Simvastatina", value: "Simvastatina" },
    { label: "Rosuvastatina", value: "Rosuvastatina" },
    { label: "Ramipril", value: "Ramipril" },
    { label: "Losartana", value: "Losartana" },
    { label: "Metoprolol", value: "Metoprolol" },
    { label: "Carvedilol", value: "Carvedilol" },
    { label: "Furosemida", value: "Furosemida" },
    { label: "Hidroclorotiazida", value: "Hidroclorotiazida" },
    { label: "Enalapril", value: "Enalapril" },
    { label: "Clopidogrel", value: "Clopidogrel" },
    { label: "Warfarina", value: "Warfarina" },
    { label: "Rivaroxabana", value: "Rivaroxabana" },
    { label: "Apixabana", value: "Apixabana" },
    { label: "Prasugrel", value: "Prasugrel" },
    { label: "Ticagrelor", value: "Ticagrelor" },
    { label: "Sacubitril/Valsartana", value: "Sacubitril/Valsartana" }
  ];
  
  export default MedicationsList;
  